
blog:
    path: /blog
    # the controller value has the format 'controller_class::method_name
    controller: Mybasicmodule\Controller\CommentController::indexAction
blog_list:
    path: /blog/list
    # the controller value has the format 'controller_class::method_name
    controller: Mybasicmodule\Controller\CommentController::listAction
blog_update:
    path: /blog/update/{id}
    # the controller value has the format 'controller_class::method_name
    controller: Mybasicmodule\Controller\CommentController::updateAction
